language: scala

scala:
  - 2.11.11

jdk:
  - oraclejdk8

branches:
  only:
    - master

before_script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi"

script:
  - sbt ++$TRAVIS_SCALA_VERSION package

after_success:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

env:
  global:
    - COURSIER_PROGRESS=0
